### ISSUE TITLE
nuxt2 に進化して、babel7 使えるといいなぁ。笑（opmlブランチ がマージできる）

### ISSUE THREAD

**Issue by yahsan2** [noracast/podcast-freaks#6]

**Comment by naokazuterada** [comment]
こちらで手を付け始めてます！
https://github.com/noracast/podcast-freaks/tree/nuxt2

**Comment by naokazuterada** [comment]
bba02c7286cca3d8d13527e2a43941985b936b8f

nuxt2にしたもので、masterを置き換えました。旧masterブランチは `z-archive/nuxt1` に残しています。
