### ISSUE TITLE
Cast for Fun の "Open Web" リンクが HP を指していない

### ISSUE THREAD

**Issue by suginoy** [noracast/podcast-freaks#67]
![Screen Shot 2019-05-04 at 18 21 16](https://user-images.githubusercontent.com/689830/57177020-b740b180-6e9a-11e9-826b-6a748d088a4f.jpg)

- `prebuild.js` の問題はなく、RSS フィード内の値が正しくないようです。
- `https://cast-for.fun/feed.xml` を見ると、`<channel>` タグ内が以下になっていればよいようです。

```diff
-<link>https://cast-for.fun/feed.xml</link>
+<link>https://cast-for.fun</link>
```

ref https://cyber.harvard.edu/rss/rss.html#requiredChannelElements

ブログ( https://pensuke.work/posts/cast-for-fun ) からはリポジトリが探せなかったので、配信者に直接連絡した方がよいのかなぁと。

**Comment by naokazuterada** [comment]
おおお、こんなところまで見ていただいて恐縮です！
これは配信者さんに報告するのが良いですね。私の方でコンタクトを取ってみます！

**Comment by pensuke81** [comment]
@suginoy @naokazuterada ありがとうございます！確認させていただきました。

直してみたので、うまいこといってたら次のデプロイ時に直るのではないかと思います...！

**Comment by pensuke81** [comment]
別件ですがPR投げさせていただいておりまして、そのDeployで正しく動いていることを確認いたしました！
https://5cce67cfca5d4b000820b18b--podcast-freaks.netlify.com/

<img src="https://user-images.githubusercontent.com/44516902/57188545-a431ee00-6f3b-11e9-8c04-dce6926074ac.png" width="250px">

**Comment by naokazuterada** [comment]
ありがとうございます！こちらでも確認しました。
PRの方もマージしておいたので、少ししたらproductionにも反映されるはずです。
問題はなくなりましたので、closeします！

**Comment by suginoy** [comment]
😃
